services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_NAME: eventdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    volumes:
      - .:/app

volumes:
  pgdata:
